/**************************************************************
 ********          THIS IS A GENERATED FILE         ***********
 **************************************************************/

#ifndef QDM_QEO_TYPES_H_
#define QDM_QEO_TYPES_H_

#include <qeo/types.h>


/**
 * this is the device ID generated by Qeo.
 */
typedef struct {
    /**
     * Upper 64-bit of identifier.
     */
    int64_t upper;
    /**
     * Lower 64-bit of identifier.
     */
    int64_t lower;
} org_qeo_system_DeviceId_t;
extern const DDS_TypeSupport_meta org_qeo_system_DeviceId_type[];

/**
 * A generic 128-bit UUID.
 */
typedef struct {
    /**
     * Upper 64-bit of identifier.
     */
    int64_t upper;
    /**
     * Lower 64-bit of identifier.
     */
    int64_t lower;
} org_qeo_UUID_t;
extern const DDS_TypeSupport_meta org_qeo_UUID_type[];


#endif /* QDM_QEO_TYPES_H_ */

